// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz36chS8eQ2ILzpVlIbtw-aPUgLb9fzEs',
    appId: '1:914942804300:web:4913dede56b89bf6bfcfe9',
    messagingSenderId: '914942804300',
    projectId: 'healtharcade',
    authDomain: 'healtharcade.firebaseapp.com',
    storageBucket: 'healtharcade.firebasestorage.app',
    measurementId: 'G-MPYT7D63MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEIPnhcPwa4eabkvCFfV4M5gX-YiR4mJU',
    appId: '1:914942804300:android:3d99f0b5ded01cfbbfcfe9',
    messagingSenderId: '914942804300',
    projectId: 'healtharcade',
    storageBucket: 'healtharcade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXP2lcMHTgEIje0CA3-rZtw3yySYIzWP8',
    appId: '1:914942804300:ios:a7f1c9ca00d11890bfcfe9',
    messagingSenderId: '914942804300',
    projectId: 'healtharcade',
    storageBucket: 'healtharcade.firebasestorage.app',
    iosBundleId: 'com.example.healtharcadia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXP2lcMHTgEIje0CA3-rZtw3yySYIzWP8',
    appId: '1:914942804300:ios:a7f1c9ca00d11890bfcfe9',
    messagingSenderId: '914942804300',
    projectId: 'healtharcade',
    storageBucket: 'healtharcade.firebasestorage.app',
    iosBundleId: 'com.example.healtharcadia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz36chS8eQ2ILzpVlIbtw-aPUgLb9fzEs',
    appId: '1:914942804300:web:3d3ddb3bc52fa00cbfcfe9',
    messagingSenderId: '914942804300',
    projectId: 'healtharcade',
    authDomain: 'healtharcade.firebaseapp.com',
    storageBucket: 'healtharcade.firebasestorage.app',
    measurementId: 'G-Y1LE6Z012Z',
  );
}
